[project]
name = "food"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.37.0",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "seaborn>=0.13.2",
    "torch>=2.7.1",
    "ultralytics>=8.3.166",
]
